### ISSUE TITLE
Create a CSC hackathon planning kit

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#152]
Please add your feedback regarding how the hackathon was run, how it was organised and how it should be done. The end result of this issue will be a practical planning kit that we can put on the website and follow for future hackathons.

**Comment by dangerdika** [comment]
@GSTT-CSC/core

**Comment by hshuaib90** [comment]
- [ ] have a scrum master type that is responsible for making sure everyone is working productively

**Comment by dangerdika** [comment]
@GSTT-CSC/core does anyone else have any feedback on what they liked or didnt like about the hackathon?

**Comment by Lucrezia-Cester** [comment]
Loved the pair programming with Dika and Sarah Blake.

**Comment by AnilMistry** [comment]
**Positives:** 

- Group work with a range of staff, enjoyed the large presence of clinicians involved, they were great for QMS/Documentation.
- Thinking about brading/logos/names, adds to the excitement of the project, also makes the output presentable to others after the hackathon, allows you to feel confident in sharing with other people.
- Having application experts (XNAT, MLOPs QMS) floating around both groups. 
- check ins were useful. 
- bronze, silver, gold, platinum medals were a good idea. Could this be standardised for all AIDE related hackathons?


**Negatives:**
- More planning in the first couple of hours of the hackathon was needed, espeically for the QMS. 
- Exploratory analysis of image sets should have been encouraged beforehand (it probably was, but i didnt get round to it!) 
- Repetition of work - e.g. everyone creating the dataloader for MLOps training. We got over this by the end, by sharing work across teams for QMS activities, branding, diagrams etc.

**Comment by AgatheZ** [comment]
What I liked:
* Working on an end-to-end process from data access to AIDE integration 
* Taking advantage of everyone's area of expertise to upskill myself 
* Being able to contribute just like any other CSC member 

What could be improved in my opinion:
* Lost a lot of time taking Laurence's time due to our lack of familiarity with MLOps 
* We did actually not enforce Dika's schedule and ended up all working on the same task separately - we need a better organization within the teams

**Comment by aysha1207** [comment]
Positive
- It was great to work with different members of the group that I don't normally get to work with
- Learn more about QMS 
- Being able to contribute more when compared with the previous hackathon

Suggestions for improvements
- Agree with Anil's comments - more planning/organisation at the start of the hackathon 
- Repetition especially with the QMS documentation

**Comment by heyhaleema** [comment]
**What I liked**
- Working through a full end-to-end model development process, including data ingestion, MLOps, documentation, etc.
- Having the opportunity to learn more from subject matter experts (SMEs) about their areas within the process, particularly if we hadn't had the chance to do so before.
- Pair programming!
- Different, reasonable Hackathon achievement tiers.

**What I think could be improved**
- Having a Scrum Master to track who's doing what, their progress, and how this aligns with the Hackathon's milestones/goals.

**General thoughts for future Hackathons**
- If applicable, I think it would be helpful to have pre-Hackathon prep one-pagers sent out a week before, e.g. installation guide, known issues to bear in mind going into Hackathon, etc., so that we can dive into questions/troubleshooting on the first day, if any.
- If the Hackathons involve 2+ teams, I think the SMEs would better placed to work as floating, general members of each team so that they're able to (1) allocate their time more flexibly depending on the needs of each team and (2) identify what issues each team is facing so that this can be discussed in the next checkpoint/standup.
- Dedicated Teams/Slack channels to post updates, common issues, fixes, etc. so everyone has access to these (vs. individually gained/noted down).

**Comment by laurencejackson** [comment]
What I liked

- It was good to see other people using the MLOps processes, this is the first time a lot of people used it and it showed how well it would work when used in anger! some things need to be rethought but overall useful from that point of view
- Having all the data prepared was a massive boost to us being ready to go on the day
- I liked the competitiveness! but teams were maybe just on the small side for the amount of work we needed to do.

What I think could be improved

- Data import takes too long for rapid turnaround - but that's an mlops problem really
- Development activity could have been better organised. I think we all worked on features but easily lost sync with the rest of the team. We could make better use of the GitHub milestones/project boards in advance of the hackathons to distribute work.
