### ISSUE TITLE
XNAT calculator to be added to the website for transparent pricing

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/csc-test-site#173]
The prices already agreed but want to have an estimator - not quote generator - on the CSC website

**Comment by heyhaleema** [comment]
Similar to #207, it currently seems like the easiest option would be to embed a calculator e.g., a Microsoft Excel workbook:

https://user-images.githubusercontent.com/67117138/233439694-4fa2fe23-3928-4b32-8275-5d325f4e9090.mov

However, like with Microsoft Forms, we should discuss:
- What GSTT or KCL email is the Microsoft Excel workbook tied to?
- Is this the right approach since the embedded link we use would (1) reveal the user's email address ID (unless there's a way to store and access this as a secret) and (2) that link would need to be enabled for anyone to access i.e., to not require a Microsoft sign-in on the website?

Unlike building it in HTML, however, it might be easier to update the logic e.g., add new services, update rates, etc. in the workbooks.

@dangerdika @hshuaib90 Thoughts?
