### ISSUE TITLE
Add KnowledgeBase/FAQ to store knowledge

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/csc-test-site#190]
This response to Tom's query regarding X-ray segmentations and RTStruct is incredibly informative and it would be great if we had a location to include little bits of knowledge like this.

https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin/issues/41/unable-to-create-rtstruct-from-x-ray-dicom

**Comment by hshuaib90** [comment]
http://www.doingpresentations.com

**Comment by heyhaleema** [comment]
@hshuaib90 Just to clarify, do you mean create a new "Knowledge Base" sub-section e.g., under the About Us or Projects sections, or store these knowledge bases in an existing sub-section e.g., Handbook or Guides? IMO, I think topics like [that query](https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin/issues/41/unable-to-create-rtstruct-from-x-ray-dicom) are best stored in a RTD site and then linked to from the website because it has the potential to become more detailed.

**Comment by hshuaib90** [comment]
Yes, if we had a bespoke RTD website then sure, although what would be the added benefit of RTD? Most of these entries would be manual and not project specific - whereas RTD is automated and builds from CI/CD.

**Comment by dangerdika** [comment]
Closing this issue as we have substituted it with the 'useful resources' section on the Notion
